### ISSUE TITLE
자신감 파라미터 목소리 떨림 잡기

### ISSUE THREAD

**Issue by woog2ee** [idealization/Jasmine#19]
목소리 톤 및 떨림 잡는 코드 개발

**Comment by bo-lim** [comment]
oursera.org/programs/cca0b3aa-1f77-432c-a4e6-7f333cf49a48/browse?currentTab=CATALOG&productId=W62RsyrdEeeFQQqyuQaohA&productType=s12n&query=DeepLearning&showMiniModal=true
