### ISSUE TITLE
face landmark 값이랑 gaze 값 오류

### ISSUE THREAD

**Issue by idealization** [idealization/Jasmine#26]
비전이 맥북에선 정상적으로 작동하는데 삼성거만 안 된다..(?)
아님 그냥 보림이거만 되는 건가..?
아님 코드를 잘 못 짠 건가....? <- 제일 가능성 높음

**Comment by bo-lim** [comment]
이것도 카메라 1개로 합치면서 gaze-detection을 커스텀마이징하여 기적적으로 완료했슴당~!!
